language: julia

os:
  - linux
  - osx

julia:
  - 1.0
  - 1.1
  - nightly

notifications:
  email: false

matrix:
  allow_failures:
    - julia: 1.1
    - julia: nightly

script:
  - julia --project --check-bounds=yes -e 'import Pkg; Pkg.build(); Pkg.test("JuliaPackageTemplate"; coverage=true)'

# After successfuly build submit coverage report and deploy updated documentation
# But limit deployment to the linux worker so this is done only once.
after_success:
  # Install required packages for coverage and documentation
  - julia --project -e 'import Pkg; Pkg.add("Coverage");''

  # Submit test coverage report
  - julia --project -e 'using Coverage; Coveralls.submit(Coveralls.process_folder())'

  # Install packages required for documentation generation
  - julia --project -e 'import Pkg; Pkg.add("Documenter"); Pkg.add("DocumenterTools");'
  - julia --project -e 'import Pkg; Pkg.add("PGFPlots"); Pkg.add("Plots");'

  # Build and deploy documentation
  - julia --project ./docs/make.jl